language: scala

scala:
   - 2.10.4
   - 2.11.6

services:
  - cassandra
  - mongodb

before_install:
    - wget https://github.com/miguel0afd/crossdata/blob/mongoDep/dependencies/spark-mongodb_2.10-0.10.0-20151021.142856-5.jar
    - wget https://github.com/miguel0afd/crossdata/blob/mongoDep/dependencies/spark-mongodb_2.11-0.10.0-20151021.142858-5.jar
    - mvn install:install-file -Dfile=spark-mongodb_2.10-0.10.0-20151021.142856-5.jar
    - mvn install:install-file -Dfile=spark-mongodb_2.11-0.10.0-20151021.142858-5.jar

script:

  - mvn test -Dmaven.test.failure=true

after_success:
  - bash <(curl -s https://codecov.io/bash)
