language: scala

scala:
   - 2.10.4
   - 2.11.6

services:
  - cassandra
  - mongodb

before_install:
    - git clone https://github.com/Stratio/spark-mongodb.git
    - cd spark-mongodb
    - mvn -q install -DskipUTs -DskipITs -DskipTests


script:

  - mvn -q test -Dmaven.test.failure=true

after_success:
  - bash <(curl -s https://codecov.io/bash)
